### ISSUE TITLE
Recommended package but doesn't work with Flame 1.0

### ISSUE THREAD

**Issue by vguzzi** [flame-engine/flame_tiled#11]
`flame_tiled` is recommended [here](https://flame-engine.org/docs/#/) underneath `flame_forge2d` which requires >Flame 1.0, but flame_tiled 0.1.0 isn't compatible with flame 1.0. Are we meant to use the standard `tiled` API and ignore the docs?

**Comment by luanpotter** [comment]
It does now! Moved to https://github.com/flame-engine/flame/tree/main/packages/flame_tiled
