### ISSUE TITLE
Map not loading post Tiled update refactoring tileset source

### ISSUE THREAD

**Issue by pgainullin** [flame-engine/flame_tiled#3]
This line triggers an error:

https://github.com/flame-engine/flame_tiled/blob/e7b040ccf8dbeb77714d496622b8c52fade42b99/lib/tiled.dart#L91

```
E/flutter ( 4975): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The getter 'source' was called on null.
E/flutter ( 4975): Receiver: null
E/flutter ( 4975): Tried calling: source
E/flutter ( 4975): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 4975): #1      TiledComponent._load (package:flame/components/tiled_component.dart:91:59)
E/flutter ( 4975): <asynchronous suspension>
E/flutter ( 4975): #2      new TiledComponent (package:flame/components/tiled_component.dart:86:14)

```

This seems to be due to the recent update of the Tiled format where the .tmx file now references the .tsx tileset file instead of the tileset image directly.

Before:

```
<tileset firstgid="1" name="tileset" tilewidth="32" tileheight="32" tilecount="72" columns="3">
<image source="tileset.png" width="96" height="768"/>

```
Now:

`<tileset firstgid="1" source="tileset.tsx"/>
`

**Comment by luanpotter** [comment]
@pgainullin do you have more details on this "upgraded" version of the tsx format? is it versioned? did they make an incompatible breaking change? do we need to support both versions for older files?

**Comment by pgainullin** [comment]
I can't pinpoint where the change was made but based on the docs both formats are still supported by Tiled:

https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tmx-tileset

The change in the way the tileset gets saved occurred to me after updating from v.1.3.5 to v.1.4.2 (https://github.com/bjorn/tiled/releases) but the diff there is massive and I can't seem to find where exactly the change took place.

**Comment by luanpotter** [comment]
We will probably need to some code to check and support both paths then. If you would like to help with a PR that would be much appreciated, I might try to take a look at it later this week. If you have samples of files from the old and new version, using the offending feature, to use as tests that would be great as well.

**Comment by pgainullin** [comment]
Sure, I've just added a minimal project with the two sample files: https://github.com/pgainullin/tiled_test

Incidentally it also shows that staggered hex maps don't work correctly at the moment which in my other project I fix by manually offsetting the files and saving their position values in a separate data structure, but that's obviously a separate issue.

I'm not sure I'm capable of creating a PR for this myself, but I'll try to find time and delve into it.

**Comment by pgainullin** [comment]
Now starting to look at the structure and it seems changes will be needed to the TileMapParser here https://github.com/flame-engine/tiled.dart and not just the flame_tiled

**Comment by pgainullin** [comment]
Started a PR for this, but haven't tested is at all yet - https://github.com/flame-engine/flame_tiled/compare/master...pgainullin:pgainullin-patch-tsx

**Comment by luanpotter** [comment]
that looks good to me overall, feel free to open a PR with that change :)
