### ISSUE TITLE
Bit shifts processing tile flips break down around gid=>2^28

### ISSUE THREAD

**Issue by pgainullin** [flame-engine/flame_tiled#4]
See this example including sample data:

https://gist.github.com/pgainullin/bdf8ac141e9501958c993bb4467685fb

Running it in DartPad shows several IDs turn to 268435492 and 268435498 post flag-clearing. Given that there are bit shifts in this code and 2^28=268435456 it looks like some sort of an overflow error.

I can't see any issues just by looking at the code in tiled/src/layer.dart assempleTileMatrix vs the docs (https://doc.mapeditor.org/en/stable/reference/tmx-map-format/) but I don't know enough about bitwise operations in Dart to really understand it

**Comment by luanpotter** [comment]
This is an issue with the underlying https://github.com/flame-engine/tiled.dart/ library, not with flame_tiled. I will link this issue there, and close this one.
